### ISSUE TITLE
Method not found: 'System.Text.StringBuilder System.Text.StringBuilder.AppendFormat(System.String, System.Object)'.

### ISSUE THREAD

**Issue by asdf23** [punitganshani/CodeInject#9]
If I inject a log4net into my assembly I get an error requiring StringBuilder

```
Message: System.MissingMethodException: Method not found: 'System.Text.StringBuilder System.Text.StringBuilder.AppendFormat(System.String, System.Object)'.
   at CInject.Injections.Injectors.LogInject.OnInvoke(CInjection injection)
   at myClass.Class1.GetText()
   at myProject.MainPage.userControl_Loaded(Object sender, RoutedEventArgs e)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(UInt32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName, UInt32 flags)     
') occurred in myProject.exe
```

**Comment by punitganshani** [comment]
What version of .NET are you using and what version of .NET is installed on your desktop?

This needs min `.NET 4.5` to run

**Comment by Praful-karkar** [comment]
already using 4.5.2 framework version same error occurs in client pc also have a same framework
 Please Help Me
